<!---
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->
<h1 id="apache-spark-1.2.2-release-notes">Apache Spark 1.2.2 Release Notes</h1>
<p>These release notes cover new developer and user-facing incompatibilities, features, and major improvements.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-7027">SPARK-7027</a> | <em>Critical</em> | <strong>Spark 1.2.2 Hadoop 2.4 download is missing</strong></li>
</ul>
<p>Can't download Spark 1.2.2 pre-built for Hadoop 2.4 from https://spark.apache.org/downloads.html.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6878">SPARK-6878</a> | <em>Minor</em> | <strong>Sum on empty RDD fails with exception</strong></li>
</ul>
<p>{{Sum}} on an empty RDD throws an exception. Expected result is {{0}}.</p>
<p>A simple fix is the replace</p>
<p>{noformat} class DoubleRDDFunctions { def sum(): Double = self.reduce(_ + _) {noformat}</p>
<p>with:</p>
<p>{noformat} class DoubleRDDFunctions { def sum(): Double = self.aggregate(0.0)(_ + _, _ + _) {noformat}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6667">SPARK-6667</a> | <em>Blocker</em> | <strong>hang while collect in PySpark</strong></li>
</ul>
<p>PySpark tests hang while collecting:</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6578">SPARK-6578</a> | <em>Blocker</em> | <strong>Outbound channel in network library is not thread-safe, can lead to fetch failures</strong></li>
</ul>
<p>There is a very narrow race in the outbound channel of the network library. While netty guarantees that the inbound channel is thread-safe, the same is not true for the outbound channel: multiple threads can be writing and running the pipeline at the same time.</p>
<p>This leads to an issue with MessageEncoder and the optimization it performs for zero-copy of file data: since a single RPC can be broken into multiple buffers (for , example when replying to a chunk request), if you have multiple threads writing these RPCs then they can be mixed up in the final socket. That breaks framing and will cause the receiving side to not understand the messages.</p>
<p>Patch coming up shortly.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6480">SPARK-6480</a> | <em>Major</em> | <strong>histogram() bucket function is wrong in some simple edge cases</strong></li>
</ul>
<p>(Credit to a customer report here) This test would fail now:</p>
<p>{code} val rdd = sc.parallelize(Seq(1, 1, 1, 2, 3, 3)) assert(Array(3, 1, 2) === rdd.map(_.toDouble).histogram(3)._2) {code}</p>
<p>Because it returns 3, 1, 0. The problem ultimately traces to the 'fast' bucket function that judges buckets based on a multiple of the gap between first and second elements. Errors multiply and the end of the final bucket fails to include the max.</p>
<p>Fairly plausible use case actually.</p>
<p>This can be tightened up easily with a slightly better expression. It will also fix this test, which is actually expecting the wrong answer:</p>
<p>{code} val rdd = sc.parallelize(6 to 99) val (histogramBuckets, histogramResults) = rdd.histogram(9) val expectedHistogramResults = Array(11, 10, 11, 10, 10, 11, 10, 10, 11) {code}</p>
<p>(Should be {{Array(11, 10, 10, 11, 10, 10, 11, 10, 11)}})</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6414">SPARK-6414</a> | <em>Critical</em> | <strong>Spark driver failed with NPE on job cancelation</strong></li>
</ul>
<p>When a job group is cancelled, we scan through all jobs to determine which are members of the group. This scan assumes that the job group property is always set. If 'properties' is null in an active job, you get an NPE.</p>
<p>We just need to make sure we ignore ones where activeJob.properties is null. We should also make sure it works if the particular property is missing.</p>
<p>https://github.com/apache/spark/blob/branch-1.3/core/src/main/scala/org/apache/spark/scheduler/DAGScheduler.scala#L678</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6313">SPARK-6313</a> | <em>Critical</em> | <strong>Fetch File Lock file creation doesnt work when Spark working dir is on a NFS mount</strong></li>
</ul>
<p>When running in cluster mode and mounting the spark work dir on a NFS volume (or some volume which doesn't support file locking), the fetchFile (used for downloading JARs etc on the executors) method in Spark Utils class will fail. This file locking was introduced as an improvement with SPARK-2713.</p>
<p>See https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/util/Utils.scala#L415</p>
<p>Introduced in 1.2 in commit; https://github.com/apache/spark/commit/7aacb7bfad4ec73fd8f18555c72ef696</p>
<p>As this locking is for optimisation for fetching files, could we take a different approach here to create a temp/advisory lock file?</p>
<p>Typically you would just mount local disks (in say ext4 format) and provide this as a comma separated list however we are trying to run Spark on MapR. With MapR we can do a loop back mount to a volume on the local node and take advantage of MapRs disk pools. This also means we dont need specific mounts for Spark and improves the generic nature of the cluster.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6294">SPARK-6294</a> | <em>Critical</em> | <strong>PySpark task may hang while call take() on in Java/Scala</strong></li>
</ul>
<p>{code} &gt;&gt;&gt; rdd = sc.parallelize(range(1&lt;&lt;20)).map(lambda x: str(x)) &gt;&gt;&gt; rdd._jrdd.first() {code}</p>
<p>There is the stacktrace while hanging:</p>
<p>{code} &quot;Executor task launch worker-5&quot; daemon prio=10 tid=0x00007f8fd01a9800 nid=0x566 in Object.wait() [0x00007f90481d7000] java.lang.Thread.State: WAITING (on object monitor) at java.lang.Object.wait(Native Method) - waiting on &lt;0x0000000630929340&gt; (a org.apache.spark.api.python.PythonRDD$WriterThread) at java.lang.Thread.join(Thread.java:1281) - locked &lt;0x0000000630929340&gt; (a org.apache.spark.api.python.PythonRDD$WriterThread) at java.lang.Thread.join(Thread.java:1355) at org.apache.spark.api.python.PythonRDD$$anonfun$compute$1.apply(PythonRDD.scala:78) at org.apache.spark.api.python.PythonRDD$$anonfun$compute$1.apply(PythonRDD.scala:76) at org.apache.spark.TaskContextImpl$$anon$1.onTaskCompletion(TaskContextImpl.scala:49) at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:68) at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:66) at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47) at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:66) at org.apache.spark.scheduler.Task.run(Task.scala:58) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745) {code}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6194">SPARK-6194</a> | <em>Critical</em> | <strong>collect() in PySpark will cause memory leak in JVM</strong></li>
</ul>
<p>It could be reproduced by:</p>
<p>{code} for i in range(40): sc.parallelize(range(5000), 10).flatMap(lambda i: range(10000)).collect() {code}</p>
<p>It will fail after 2 or 3 jobs, and run totally successfully if I add <code>gc.collect()</code> after each job.</p>
<p>We could call _detach() for the JavaList returned by collect in Java, will send out a PR for this.</p>
<p>Reported by Michael and commented by Joshï¼š</p>
<p>On Thu, Mar 5, 2015 at 2:39 PM, Josh Rosen &lt;joshrosen@databricks.com&gt; wrote: &gt; Based on Py4J's Memory Model page &gt; (http://py4j.sourceforge.net/advanced_topics.html#py4j-memory-model): &gt; &gt;&gt; Because Java objects on the Python side are involved in a circular &gt;&gt; reference (JavaObject and JavaMember reference each other), these objects &gt;&gt; are not immediately garbage collected once the last reference to the object &gt;&gt; is removed (but they are guaranteed to be eventually collected if the Python &gt;&gt; garbage collector runs before the Python program exits). &gt; &gt; &gt;&gt; &gt;&gt; In doubt, users can always call the detach function on the Python gateway &gt;&gt; to explicitly delete a reference on the Java side. A call to gc.collect() &gt;&gt; also usually works. &gt; &gt; &gt; Maybe we should be manually calling detach() when the Python-side has &gt; finished consuming temporary objects from the JVM. Do you have a small &gt; workload / configuration that reproduces the OOM which we can use to test a &gt; fix? I don't think that I've seen this issue in the past, but this might be &gt; because we mistook Java OOMs as being caused by collecting too much data &gt; rather than due to memory leaks. &gt; &gt; On Thu, Mar 5, 2015 at 10:41 AM, Michael Nazario &lt;mnazario@palantir.com&gt; &gt; wrote: &gt;&gt; &gt;&gt; Hi Josh, &gt;&gt; &gt;&gt; I have a question about how PySpark does memory management in the Py4J &gt;&gt; bridge between the Java driver and the Python driver. I was wondering if &gt;&gt; there have been any memory problems in this system because the Python &gt;&gt; garbage collector does not collect circular references immediately and Py4J &gt;&gt; has circular references in each object it receives from Java. &gt;&gt; &gt;&gt; When I dug through the PySpark code, I seemed to find that most RDD &gt;&gt; actions return by calling collect. In collect, you end up calling the Java &gt;&gt; RDD collect and getting an iterator from that. Would this be a possible &gt;&gt; cause for a Java driver OutOfMemoryException because there are resources in &gt;&gt; Java which do not get freed up immediately? &gt;&gt; &gt;&gt; I have also seen that trying to take a lot of values from a dataset twice &gt;&gt; in a row can cause the Java driver to OOM (while just once works). Are there &gt;&gt; some other memory considerations that are relevant in the driver? &gt;&gt; &gt;&gt; Thanks, &gt;&gt; Michael</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6167">SPARK-6167</a> | <em>Minor</em> | <strong>Previous Commit Broke BroadcastTest</strong></li>
</ul>
<p>Commit associated with SPARK-1010 spell class names incorrectly (BroaddcastFactory instead of BroadcastFactory). As a result, the BroadcastTest doesn't work.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6133">SPARK-6133</a> | <em>Major</em> | <strong>SparkContext#stop is not idempotent</strong></li>
</ul>
<p>If we call sc.stop() twice, the listener bus will attempt to log an event after stop() is called, resulting in a scary error message. This happens if Spark calls sc.stop() internally (it does this on certain error conditions) and the application code calls it again, for instance.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6132">SPARK-6132</a> | <em>Major</em> | <strong>Context cleaner race condition across SparkContexts</strong></li>
</ul>
<p>The context cleaner thread is not stopped properly. If a SparkContext is started immediately after one stops, the context cleaner of the former can clean variables in the latter.</p>
<p>This is because the cleaner.stop() just sets a flag and expects the thread to terminate asynchronously, but the code to clean broadcasts goes through <code>SparkEnv.get.blockManager</code>, which could belong to a different SparkContext. This is likely to be the cause of the <code>JavaAPISuite</code>, which creates many back-to-back SparkContexts, being flaky.</p>
<p>The right behavior is to wait until all currently running clean up tasks have finished. {code} java.io.IOException: org.apache.spark.SparkException: Failed to get broadcast_0_piece0 of broadcast_0 at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1180) at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:164) at org.apache.spark.broadcast.TorrentBroadcast._value$lzycompute(TorrentBroadcast.scala:64) at org.apache.spark.broadcast.TorrentBroadcast._value(TorrentBroadcast.scala:64) ... Caused by: org.apache.spark.SparkException: Failed to get broadcast_0_piece0 of broadcast_0 at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1$$anonfun$2.apply(TorrentBroadcast.scala:137) at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1$$anonfun$2.apply(TorrentBroadcast.scala:137) at scala.Option.getOrElse(Option.scala:120) {code}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6055">SPARK-6055</a> | <em>Blocker</em> | <strong>Memory leak in pyspark sql due to incorrect equality check</strong></li>
</ul>
<p>The __eq__ of DataType is not correct, class cache is not used correctly (created class can not be find by dataType), then it will create lots of classes (saved in _cached_cls), never released.</p>
<p>Also, all same DataType have same hash code, there will be many object in a dict with the same hash code, end with hash attach, it's very slow to access this dict (depends on the implementation of CPython).</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6033">SPARK-6033</a> | <em>Minor</em> | <strong>the description abou the &quot;spark.worker.cleanup.enabled&quot; is not matched with the code</strong></li>
</ul>
<p>Some error about the section _Cluster Launch Scripts_ in the http://spark.apache.org/docs/latest/spark-standalone.html</p>
<p>In the description about the property spark.worker.cleanup.enabled, it states that *all the directory* under the work dir will be removed whether the application is running or not.</p>
<p>After checking the implementation in the code level, I found that +only the stopped application+ dirs would be removed. So the description in the document is incorrect.</p>
<p>the code implementation in worker.scala {code: title=WorkDirCleanup} case WorkDirCleanup =&gt; // Spin up a separate thread (in a future) to do the dir cleanup; don't tie up worker actor val cleanupFuture = concurrent.future { val appDirs = workDir.listFiles() if (appDirs == null) { throw new IOException(&quot;ERROR: Failed to list files in &quot; + appDirs) } appDirs.filter { dir =&gt; // the directory is used by an application - check that the application is not running // when cleaning up val appIdFromDir = dir.getName val isAppStillRunning = executors.values.map(_.appId).contains(appIdFromDir) dir.isDirectory &amp;&amp; !isAppStillRunning &amp;&amp; !Utils.doesDirectoryContainAnyNewFiles(dir, APP_DATA_RETENTION_SECS) }.foreach { dir =&gt; logInfo(s&quot;Removing directory: ${dir.getPath}&quot;) Utils.deleteRecursively(dir) } }</p>
<pre><code>  cleanupFuture onFailure {
    case e: Throwable =\&gt;
      logError(&quot;App dir cleanup failed: &quot; + e.getMessage, e)
  }</code></pre>
<p>{code}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6018">SPARK-6018</a> | <em>Minor</em> | <strong>NoSuchMethodError in Spark app is swallowed by YARN AM</strong></li>
</ul>
<p>I discovered this bug while testing 1.3 RC with old 1.2 Spark job that I had. Due to changes in DF and SchemaRDD, my app failed with {{java.lang.NoSuchMethodError}}. However, AM was marked as succeeded, and the error was silently swallowed.</p>
<p>The problem is that pattern matching in Spark AM fails to catch NoSuchMethodError- {code} 15/02/25 20:13:27 INFO cluster.YarnClusterScheduler: YarnClusterScheduler.postStartHook done Exception in thread &quot;Driver&quot; scala.MatchError: java.lang.NoSuchMethodError: org.apache.spark.sql.hive.HiveContext.table(Ljava/lang/String;)Lorg/apache/spark/sql/SchemaRDD; (of class java.lang.NoSuchMethodError) at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:485) {code}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-6015">SPARK-6015</a> | <em>Minor</em> | <strong>Backport Python doc source code link fix to 1.2</strong></li>
</ul>
<p>The Python docs display {code}[source]{code} links which should link to source code, but none work in the documentation provided on the Apache Spark website. E.g., go here [https://spark.apache.org/docs/latest/api/python/pyspark.mllib.html#module-pyspark.mllib.regression] and click a source code link on the right.</p>
<p>The PR for [SPARK-5994] included a fix of this for 1.3 which should be backported to 1.2.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5973">SPARK-5973</a> | <em>Blocker</em> | <strong>zip two rdd with AutoBatchedSerializer will fail</strong></li>
</ul>
<p>zip two rdd with AutoBatchedSerializer will fail, this bug was introduced by SPARK-4841</p>
<p>{code} &gt;&gt; a.zip(b).count() 15/02/24 12:11:56 ERROR PythonRDD: Python worker exited unexpectedly (crashed) org.apache.spark.api.python.PythonException: Traceback (most recent call last): File &quot;/Users/davies/work/spark/python/pyspark/worker.py&quot;, line 101, in main process() File &quot;/Users/davies/work/spark/python/pyspark/worker.py&quot;, line 96, in process serializer.dump_stream(func(split_index, iterator), outfile) File &quot;/Users/davies/work/spark/python/pyspark/rdd.py&quot;, line 2249, in pipeline_func return func(split, prev_func(split, iterator)) File &quot;/Users/davies/work/spark/python/pyspark/rdd.py&quot;, line 2249, in pipeline_func return func(split, prev_func(split, iterator)) File &quot;/Users/davies/work/spark/python/pyspark/rdd.py&quot;, line 270, in func return f(iterator) File &quot;/Users/davies/work/spark/python/pyspark/rdd.py&quot;, line 933, in &lt;lambda&gt; return self.mapPartitions(lambda i: [sum(1 for _ in i)]).sum() File &quot;/Users/davies/work/spark/python/pyspark/rdd.py&quot;, line 933, in &lt;genexpr&gt; return self.mapPartitions(lambda i: [sum(1 for _ in i)]).sum() File &quot;/Users/davies/work/spark/python/pyspark/serializers.py&quot;, line 306, in load_stream &quot; in pair: (%d, %d)&quot; % (len(keys), len(vals))) ValueError: Can not deserialize RDD with different number of items in pair: (123, 64) {code}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5967">SPARK-5967</a> | <em>Blocker</em> | <strong>JobProgressListener.stageIdToActiveJobIds never cleared</strong></li>
</ul>
<p>The hashmap stageIdToActiveJobIds in JobProgressListener is never cleared. So the hashmap keep increasing in size indefinitely. This is a blocker for 24/7 running applications like Spark Streaming apps.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5889">SPARK-5889</a> | <em>Minor</em> | <strong>remove pid file in spark-daemon.sh after killing the process.</strong></li>
</ul>
<p>Currently, if the thriftserver/history server are stopped. The pid file is not deleted. The fix is trial, but it is important for some service checking relying on the file.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5846">SPARK-5846</a> | <em>Critical</em> | <strong>Spark SQL does not correctly set job description and scheduler pool</strong></li>
</ul>
<p>Spark SQL current sets the scheduler pool and job description AFTER jobs run (see https://github.com/apache/spark/blob/master/sql/hive-thriftserver/v0.13.1/src/main/scala/org/apache/spark/sql/hive/thriftserver/Shim13.scala#L168 -- which happens after calling hiveContext.sql). As a result, the description for a SQL job ends up being the SQL query corresponding to the previous job. This should be done before the job is run so the description is correct.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5825">SPARK-5825</a> | <em>Critical</em> | <strong>Failure stopping Services while command line argument is too long</strong></li>
</ul>
<p>Stopping service in <code>spark-daemon.sh</code> will confirm the process id by fuzzy matching the class name, however, it will fail if the java process arguments is very long (greater than 4096).</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5805">SPARK-5805</a> | <em>Minor</em> | <strong>Fix the type error in the final example given in MLlib - Clustering documentation</strong></li>
</ul>
<p>The final example in [MLlib - Clustering|http://spark.apache.org/docs/1.2.0/mllib-clustering.html] documentation has a code line that leads to a type error.</p>
<p>The problematic line reads as:</p>
<p>{code} model.predictOnValues(testData).print() {code}</p>
<p>but it should be</p>
<p>{code} model.predictOnValues(testData.map(lp =&gt; (lp.label, lp.features))).print() {code}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5788">SPARK-5788</a> | <em>Blocker</em> | <strong>Capture exceptions in Python write thread</strong></li>
</ul>
<p>The exception in Python writer thread will shutdown executor.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5765">SPARK-5765</a> | <em>Major</em> | <strong>word split problem in run-example and compute-classpath</strong></li>
</ul>
<p>Work split problem in spark directory path in scripts run-example and compute-classpath.sh</p>
<p>This was introduced in defect fix SPARK-4504</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5749">SPARK-5749</a> | <em>Major</em> | <strong>Fix Bash word splitting bugs in compute-classpath.sh</strong></li>
</ul>
<p>For example [this line|https://github.com/apache/spark/blob/fa6bdc6e819f9338248b952ec578bcd791ddbf6d/bin/compute-classpath.sh#L79] has a word splitting bug.</p>
<p>{code} for f in ${assembly_folder}/spark-assembly*hadoop*.jar; do if [[ ! -e &quot;$f&quot; ]]; then echo &quot;Failed to find Spark assembly in $assembly_folder&quot; 1&gt;&amp;2 echo &quot;You need to build Spark before running this program.&quot; 1&gt;&amp;2 exit 1 fi ASSEMBLY_JAR=&quot;$f&quot; num_jars=$((num_jars+1)) done {code}</p>
<p>If {{assembly_folder}} contains a space, this block of code will fail.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5728">SPARK-5728</a> | <em>Trivial</em> | <strong>MQTTStreamSuite leaves behind ActiveMQ database files</strong></li>
</ul>
<p>I've seen this several times and finally wanted to fix it: {{MQTTStreamSuite}} uses a local ActiveMQ broker, that creates a working dir for its database in the {{external/mqtt}} directory called {{activemq}}. This doesn't get cleaned up, at least often it does not for me. It's trivial to set it to use a temp directory which the test harness does clean up.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5722">SPARK-5722</a> | <em>Major</em> | <strong>Infer_schema_type incorrect for Integers in pyspark</strong></li>
</ul>
<p>The Integers datatype in Python does not match what a Scala/Java integer is defined as. This causes inference of data types and schemas to fail when data is larger than 2^32 and it is inferred incorrectly as an Integer.</p>
<p>Since the range of valid Python integers is wider than Java Integers, this causes problems when inferring Integer vs. Long datatypes. This will cause problems when attempting to save SchemaRDD as Parquet or JSON.</p>
<p>Here's an example: {code} &gt;&gt;&gt; sqlCtx = SQLContext(sc) &gt;&gt;&gt; from pyspark.sql import Row &gt;&gt;&gt; rdd = sc.parallelize([Row(f1='a', f2=100000000000000)]) &gt;&gt;&gt; srdd = sqlCtx.inferSchema(rdd) &gt;&gt;&gt; srdd.schema() StructType(List(StructField(f1,StringType,true),StructField(f2,IntegerType,true))) {code} That number is a LongType in Java, but an Integer in python. We need to check the value to see if it should really by a LongType when a IntegerType is initially inferred.</p>
<p>More tests: {code} &gt;&gt;&gt; from pyspark.sql import _infer_type</p>
<h1 id="ok">OK</h1>
<p>&gt;&gt;&gt; print _infer_type(1) IntegerType</p>
<h1 id="ok-1">OK</h1>
<p>&gt;&gt;&gt; print _infer_type(2**31-1) IntegerType</p>
<h1 id="wrong">WRONG</h1>
<p>&gt;&gt;&gt; print _infer_type(2**31)</p>
<h1 id="wrong-1">WRONG</h1>
<p>IntegerType &gt;&gt;&gt; print _infer_type(2**61 )</p>
<h1 id="ok-2">OK</h1>
<p>IntegerType &gt;&gt;&gt; print _infer_type(2**71 ) LongType {code}</p>
<p>Java Primitive Types defined: http://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html</p>
<p>Python Built-in Types: https://docs.python.org/2/library/stdtypes.html#typesnumeric</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5703">SPARK-5703</a> | <em>Critical</em> | <strong>AllJobsPage throws empty.max error</strong></li>
</ul>
<p>In JobProgressListener, if you have a JobEnd that does not have a corresponding JobStart, AND you render the AllJobsPage, then you'll run into the empty.max exception.</p>
<p>I ran into this when trying to replay parts of an event log after trimming a few events. Not a common use case I agree, but I'd argue that it should never fail on empty.max.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5698">SPARK-5698</a> | <em>Critical</em> | <strong>Dynamic allocation: do not allow user to request a negative delta</strong></li>
</ul>
<p>If the user calls the following in series:</p>
<p>sc.requestExecutors(-5) sc.killExecutor(...)</p>
<p>Then we might crash the ApplicationMaster. Why?</p>
<p>Well, if we request a negative number of additional executors, then the YarnAllocator will lower the target number of executors it is trying to achieve by 5. This might shoot the target number past 0. Then, if so, when we try to kill an executor it will fail the assertion that the target number must be &gt;=0.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5691">SPARK-5691</a> | <em>Major</em> | <strong>Preventing duplicate registering of an application has incorrect logic</strong></li>
</ul>
<p>If an application registers twice with the Master, the Master accepts both copies and they both show up in the UI and consume resources. This is incorrect behavior.</p>
<p>This happens inadvertently in regular usage when the Master is under high load, but it boils down to: when an application times out registering with the master and sends a second registration message, but the Master is still alive, it processes the first registration message for the application but also erroneously processes the second registration message instead of discarding it.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5679">SPARK-5679</a> | <em>Critical</em> | <strong>Flaky tests in o.a.s.metrics.InputOutputMetricsSuite: input metrics with interleaved reads and input metrics with mixed read method</strong></li>
</ul>
<p>Please audit these and see if there are any assumptions with respect to File IO that might not hold in all cases. I'm happy to help if you can't find anything.</p>
<p>These both failed in the same run: https://amplab.cs.berkeley.edu/jenkins/view/Spark/job/Spark-1.3-SBT/38/AMPLAB_JENKINS_BUILD_PROFILE=hadoop2.2,label=centos/#showFailuresLink</p>
<p>{code} org.apache.spark.metrics.InputOutputMetricsSuite.input metrics with mixed read method</p>
<p>Failing for the past 13 builds (Since Failed#26 ) Took 48 sec. Error Message</p>
<p>20300000 did not equal 6496 Stacktrace</p>
<p>sbt.ForkMain$ForkError: 20300000 did not equal 6496 at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500) at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1555) at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466) at org.apache.spark.metrics.InputOutputMetricsSuite$$anonfun$9.apply$mcV$sp(InputOutputMetricsSuite.scala:135) at org.apache.spark.metrics.InputOutputMetricsSuite$$anonfun$9.apply(InputOutputMetricsSuite.scala:113) at org.apache.spark.metrics.InputOutputMetricsSuite$$anonfun$9.apply(InputOutputMetricsSuite.scala:113) at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22) at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85) at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104) at org.scalatest.Transformer.apply(Transformer.scala:22) at org.scalatest.Transformer.apply(Transformer.scala:20) at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166) at org.scalatest.Suite$class.withFixture(Suite.scala:1122) at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555) at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163) at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175) at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175) at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306) at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175) at org.apache.spark.metrics.InputOutputMetricsSuite.org$scalatest$BeforeAndAfter$$super$runTest(InputOutputMetricsSuite.scala:46) at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200) at org.apache.spark.metrics.InputOutputMetricsSuite.runTest(InputOutputMetricsSuite.scala:46) at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208) at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208) at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413) at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) at scala.collection.immutable.List.foreach(List.scala:318) at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396) at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483) at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208) at org.scalatest.FunSuite.runTests(FunSuite.scala:1555) at org.scalatest.Suite$class.run(Suite.scala:1424) at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555) at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212) at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212) at org.scalatest.SuperEngine.runImpl(Engine.scala:545) at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212) at org.apache.spark.metrics.InputOutputMetricsSuite.org$scalatest$BeforeAndAfterAll$$super$run(InputOutputMetricsSuite.scala:46) at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257) at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256) at org.apache.spark.metrics.InputOutputMetricsSuite.org$scalatest$BeforeAndAfter$$super$run(InputOutputMetricsSuite.scala:46) at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241) at org.apache.spark.metrics.InputOutputMetricsSuite.run(InputOutputMetricsSuite.scala:46) at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:462) at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:671) at sbt.ForkMain$Run$2.call(ForkMain.java:294) at sbt.ForkMain$Run$2.call(ForkMain.java:284) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745) {code}</p>
<p>Second one:</p>
<p>{code} org.apache.spark.metrics.InputOutputMetricsSuite.input metrics with interleaved reads</p>
<p>Failing for the past 13 builds (Since Failed#26 ) Took 19 sec. Error Message</p>
<p>2125000 did not equal 2000040 Stacktrace</p>
<p>sbt.ForkMain$ForkError: 2125000 did not equal 2000040 at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500) at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1555) at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466) at org.apache.spark.metrics.InputOutputMetricsSuite$$anonfun$31.apply$mcV$sp(InputOutputMetricsSuite.scala:289) at org.apache.spark.metrics.InputOutputMetricsSuite$$anonfun$31.apply(InputOutputMetricsSuite.scala:254) at org.apache.spark.metrics.InputOutputMetricsSuite$$anonfun$31.apply(InputOutputMetricsSuite.scala:254) at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22) at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85) at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104) at org.scalatest.Transformer.apply(Transformer.scala:22) at org.scalatest.Transformer.apply(Transformer.scala:20) at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166) at org.scalatest.Suite$class.withFixture(Suite.scala:1122) at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555) at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163) at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175) at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175) at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306) at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175) at org.apache.spark.metrics.InputOutputMetricsSuite.org$scalatest$BeforeAndAfter$$super$runTest(InputOutputMetricsSuite.scala:46) at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200) at org.apache.spark.metrics.InputOutputMetricsSuite.runTest(InputOutputMetricsSuite.scala:46) at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208) at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208) at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413) at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) at scala.collection.immutable.List.foreach(List.scala:318) at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396) at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483) at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208) at org.scalatest.FunSuite.runTests(FunSuite.scala:1555) at org.scalatest.Suite$class.run(Suite.scala:1424) at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555) at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212) at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212) at org.scalatest.SuperEngine.runImpl(Engine.scala:545) at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212) at org.apache.spark.metrics.InputOutputMetricsSuite.org$scalatest$BeforeAndAfterAll$$super$run(InputOutputMetricsSuite.scala:46) at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257) at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256) at org.apache.spark.metrics.InputOutputMetricsSuite.org$scalatest$BeforeAndAfter$$super$run(InputOutputMetricsSuite.scala:46) at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241) at org.apache.spark.metrics.InputOutputMetricsSuite.run(InputOutputMetricsSuite.scala:46) at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:462) at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:671) at sbt.ForkMain$Run$2.call(ForkMain.java:294) at sbt.ForkMain$Run$2.call(ForkMain.java:284) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745) {code}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5655">SPARK-5655</a> | <em>Critical</em> | <strong>YARN Auxiliary Shuffle service can't access shuffle files on Hadoop cluster configured in secure mode</strong></li>
</ul>
<p>When running a Spark job on a YARN cluster which doesn't run containers under the same user as the nodemanager, and also when using the YARN auxiliary shuffle service, jobs fail with something similar to: {code:java} java.io.FileNotFoundException: /data/9/yarn/nm/usercache/username/appcache/application_1423069181231_0032/spark-c434a703-7368-4a05-9e99-41e77e564d1d/3e/shuffle_0_0_0.index (Permission denied) {code}</p>
<p>The root cause of this here: https://github.com/apache/spark/blob/branch-1.2/core/src/main/scala/org/apache/spark/util/Utils.scala#L287</p>
<p>Spark will attempt to chmod 700 any application directories it creates during the job, which includes files created in the nodemanager's usercache directory. The owner of these files is the container UID, which on a secure cluster is the name of the user creating the job, and on an nonsecure cluster but with the yarn.nodemanager.container-executor.class configured is the value of yarn.nodemanager.linux-container-executor.nonsecure-mode.local-user.</p>
<p>The problem with this is that the auxiliary shuffle manager runs as part of the nodemanager, which is typically running as the user 'yarn'. This can't access these files that are only owner-readable.</p>
<p>YARN already attempts to secure files created under appcache but keep them readable by the nodemanager, by setting the group of the appcache directory to 'yarn' and also setting the setgid flag. This means that files and directories created under this should also have the 'yarn' group. Normally this means that the nodemanager should also be able to read these files, but Spark setting chmod700 wipes this out.</p>
<p>I'm not sure what the right approach is here. Commenting out the chmod700 functionality makes this work on YARN, and still makes the application files only readable by the owner and the group:</p>
<p>{code} /data/1/yarn/nm/usercache/username/appcache/application_1423247249655_0001/spark-c7a6fc0f-e5df-49cf-a8f5-e51a1ca087df/0c # ls -lah total 206M drwxr-s--- 2 nobody yarn 4.0K Feb 6 18:30 . drwxr-s--- 12 nobody yarn 4.0K Feb 6 18:30 .. -rw-r----- 1 nobody yarn 206M Feb 6 18:30 shuffle_0_0_0.data {code} But this may not be the right approach on non-YARN. Perhaps an additional step to see if this chmod700 step is necessary (ie non-YARN) is required. Sadly, I don't have a non-YARN environment to test, otherwise I'd be able to suggest a patch.</p>
<p>I believe this is a related issue in the MapReduce framwork: https://issues.apache.org/jira/browse/MAPREDUCE-3728</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5628">SPARK-5628</a> | <em>Minor</em> | <strong>Add option to return spark-ec2 version</strong></li>
</ul>
<p>We need a {{--version}} option for {{spark-ec2}}.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5613">SPARK-5613</a> | <em>Minor</em> | <strong>YarnClientSchedulerBackend fails to get application report when yarn restarts</strong></li>
</ul>
<p>Steps to Reproduce 1) Run any spark job 2) Stop yarn while the spark job is running (an application id has been generated by now) 3) Restart yarn now 4) AsyncMonitorApplication thread fails due to ApplicationNotFoundException exception. This leads to termination of thread.</p>
<p>Here is the StackTrace</p>
<p>15/02/05 05:22:37 INFO Client: Retrying connect to server: nn1/192.168.173.176:8032. Already tried 6 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS) 15/02/05 05:22:38 INFO Client: Retrying connect to server: nn1/192.168.173.176:8032. Already tried 7 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS) 15/02/05 05:22:39 INFO Client: Retrying connect to server: nn1/192.168.173.176:8032. Already tried 8 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS) 15/02/05 05:22:40 INFO Client: Retrying connect to server: nn1/192.168.173.176:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS) 5/02/05 05:22:40 INFO Client: Retrying connect to server: nn1/192.168.173.176:8032. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)</p>
<p>Exception in thread &quot;Yarn application state monitor&quot; org.apache.hadoop.yarn.exceptions.ApplicationNotFoundException: Application with id 'application_1423113179043_0003' doesn't exist in RM. at org.apache.hadoop.yarn.server.resourcemanager.ClientRMService.getApplicationReport(ClientRMService.java:284) at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationClientProtocolPBServiceImpl.getApplicationReport(ApplicationClientProtocolPBServiceImpl.java:145) at org.apache.hadoop.yarn.proto.ApplicationClientProtocol$ApplicationClientProtocolService$2.callBlockingMethod(ApplicationClientProtocol.java:321) at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:585) at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:928) at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2013) at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2009) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Unknown Source) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548) at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2007)</p>
<pre><code>at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.apache.hadoop.yarn.ipc.RPCUtil.instantiateException(RPCUtil.java:53)
at org.apache.hadoop.yarn.ipc.RPCUtil.unwrapAndThrowException(RPCUtil.java:101)
at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getApplicationReport(ApplicationClientProtocolPBClientImpl.java:166)
at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:190)
at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:103)
at com.sun.proxy.$Proxy12.getApplicationReport(Unknown Source)
at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getApplicationReport(YarnClientImpl.java:291)
at org.apache.spark.deploy.yarn.Client.getApplicationReport(Client.scala:116)
at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend$$anon$1.run(YarnClientSchedulerBackend.scala:120)</code></pre>
<p>Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.yarn.exceptions.ApplicationNotFoundException): Application with id 'application_1423113179043_0003' doesn't exist in RM. at org.apache.hadoop.yarn.server.resourcemanager.ClientRMService.getApplicationReport(ClientRMService.java:284) at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationClientProtocolPBServiceImpl.getApplicationReport(ApplicationClientProtocolPBServiceImpl.java:145) at org.apache.hadoop.yarn.proto.ApplicationClientProtocol$ApplicationClientProtocolService$2.callBlockingMethod(ApplicationClientProtocol.java:321) at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:585) at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:928) at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2013) at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2009) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Unknown Source) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548) at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2007)</p>
<pre><code>at org.apache.hadoop.ipc.Client.call(Client.java:1410)
at org.apache.hadoop.ipc.Client.call(Client.java:1363)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206)
at com.sun.proxy.$Proxy11.getApplicationReport(Unknown Source)
at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getApplicationReport(ApplicationClientProtocolPBClientImpl.java:163)
... 9 more</code></pre>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5559">SPARK-5559</a> | <em>Major</em> | <strong>Flaky test: o.a.s.streaming.flume.FlumeStreamSuite</strong></li>
</ul>
<p>When we run FlumeStreamSuite on Jenkins, sometimes we get error like as follows.</p>
<p>{code} sbt.ForkMain$ForkError: The code passed to eventually never returned normally. Attempted 52 times over 10.094849836 seconds. Last failure message: Error connecting to localhost/127.0.0.1:23456. at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:420) at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:438) at org.scalatest.concurrent.Eventually$.eventually(Eventually.scala:478) at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:307) at org.scalatest.concurrent.Eventually$.eventually(Eventually.scala:478) at org.apache.spark.streaming.flume.FlumeStreamSuite.writeAndVerify(FlumeStreamSuite.scala:116) at org.apache.spark.streaming.flume.FlumeStreamSuite.org$apache$spark$streaming$flume$FlumeStreamSuite$$testFlumeStream(FlumeStreamSuite.scala:74) at org.apache.spark.streaming.flume.FlumeStreamSuite$$anonfun$3.apply$mcV$sp(FlumeStreamSuite.scala:66) at org.apache.spark.streaming.flume.FlumeStreamSuite$$anonfun$3.apply(FlumeStreamSuite.scala:66) at org.apache.spark.streaming.flume.FlumeStreamSuite$$anonfun$3.apply(FlumeStreamSuite.scala:66) at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22) at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85) at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104) at org.scalatest.Transformer.apply(Transformer.scala:22) at org.scalatest.Transformer.apply(Transformer.scala:20) at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166) at org.scalatest.Suite$class.withFixture(Suite.scala:1122) at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555) at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163) at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175) at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175) at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306) at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175) {code}</p>
<p>This error is caused by check-then-act logic when it find free-port .</p>
<p>{code} /** Find a free port */ private def findFreePort(): Int = { Utils.startServiceOnPort(23456, (trialPort: Int) =&gt; { val socket = new ServerSocket(trialPort) socket.close() (null, trialPort) }, conf)._2 } {code}</p>
<p>Removing the check-then-act is not easy but we can reduce the chance of having the error by choosing random value for initial port instead of 23456.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5441">SPARK-5441</a> | <em>Major</em> | <strong>SerDeUtil Pair RDD to python conversion doesn't accept empty RDDs</strong></li>
</ul>
<p>SerDeUtil.pairRDDToPython and SerDeUtil.pythonToPairRDD rely on rdd.first() which throws an exception if the RDD is empty. We should be able to handle the empty RDD case because this doesn't prevent a valid RDD from being created.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5434">SPARK-5434</a> | <em>Minor</em> | <strong>Preserve spaces in path to spark-ec2</strong></li>
</ul>
<p>If the path to {{spark-ec2}} contains spaces, the script won't run.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5425">SPARK-5425</a> | <em>Major</em> | <strong>ConcurrentModificationException during SparkConf creation</strong></li>
</ul>
<p>This fragment of code:</p>
<p>{code} if (loadDefaults) { // Load any spark.* system properties for ((k, v) &lt;- System.getProperties.asScala if k.startsWith(&quot;spark.&quot;)) { settings(k) = v } } {code}</p>
<p>causes</p>
<p>{noformat} ERROR 09:43:15 SparkMaster service caused error in state STARTINGjava.util.ConcurrentModificationException: null at java.util.Hashtable$Enumerator.next(Hashtable.java:1167) ~[na:1.7.0_60] at scala.collection.convert.Wrappers$JPropertiesWrapper$$anon$3.next(Wrappers.scala:458) ~[scala-library-2.10.4.jar:na] at scala.collection.convert.Wrappers$JPropertiesWrapper$$anon$3.next(Wrappers.scala:454) ~[scala-library-2.10.4.jar:na] at scala.collection.Iterator$class.foreach(Iterator.scala:727) ~[scala-library-2.10.4.jar:na] at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) ~[scala-library-2.10.4.jar:na] at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.10.4.jar:na] at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[scala-library-2.10.4.jar:na] at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771) ~[scala-library-2.10.4.jar:na] at org.apache.spark.SparkConf.&lt;init&gt;(SparkConf.scala:53) ~[spark-core_2.10-1.2.1_dse-20150121.075638-2.jar:1.2.1_dse-SNAPSHOT] at org.apache.spark.SparkConf.&lt;init&gt;(SparkConf.scala:47) ~[spark-core_2.10-1.2.1_dse-20150121.075638-2.jar:1.2.1_dse-SNAPSHOT] {noformat}</p>
<p>when there is another thread which modifies system properties at the same time.</p>
<p>This bug https://issues.scala-lang.org/browse/SI-7775 is somehow related to the issue and shows that the problem has been also found elsewhere.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5417">SPARK-5417</a> | <em>Minor</em> | <strong>Remove redundant executor-ID set() call</strong></li>
</ul>
<p>{{spark.executor.id}} no longer [needs to be set in Executor.scala|https://github.com/apache/spark/blob/0497ea51ac345f8057d222a18dbbf8eae78f5b92/core/src/main/scala/org/apache/spark/executor/Executor.scala#L79], as of [#4194|https://github.com/apache/spark/pull/4194]; it is set upstream in [SparkEnv|https://github.com/apache/spark/blob/0497ea51ac345f8057d222a18dbbf8eae78f5b92/core/src/main/scala/org/apache/spark/SparkEnv.scala#L332]. Might as well remove the redundant set() in Executor.scala.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5395">SPARK-5395</a> | <em>Major</em> | <strong>Large number of Python workers causing resource depletion</strong></li>
</ul>
<p>During job execution a large number of Python worker accumulates eventually causing YARN to kill containers for being over their memory allocation (in the case below that is about 8G for executors plus 6G for overhead per container).</p>
<p>In this instance, at the time of killing the container 97 pyspark.daemon processes had accumulated.</p>
<p>{noformat} 2015-01-23 15:36:53,654 INFO [Reporter] yarn.YarnAllocationHandler (Logging.scala:logInfo(59)) - Container marked as failed: container_1421692415636_0052_01_000030. Exit status: 143. Diagnostics: Container [pid=35211,containerID=container_1421692415636_0052_01_000030] is running beyond physical memory limits. Current usage: 14.9 GB of 14.5 GB physical memory used; 41.3 GB of 72.5 GB virtual memory used. Killing container. Dump of the process-tree for container_1421692415636_0052_01_000030 : |- PID PPID PGRPID SESSID CMD_NAME USER_MODE_TIME(MILLIS) SYSTEM_TIME(MILLIS) VMEM_USAGE(BYTES) RSSMEM_USAGE(PAGES) FULL_CMD_LINE |- 54101 36625 36625 35211 (python) 78 1 332730368 16834 python -m pyspark.daemon |- 52140 36625 36625 35211 (python) 58 1 332730368 16837 python -m pyspark.daemon |- 36625 35228 36625 35211 (python) 65 604 331685888 17694 python -m pyspark.daemon [...] {noformat}</p>
<p>The configuration used uses 64 containers with 2 cores each.</p>
<p>Full output here: https://gist.github.com/skrasser/e3e2ee8dede5ef6b082c</p>
<p>Mailinglist discussion: https://www.mail-archive.com/user@spark.apache.org/msg20102.html</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5363">SPARK-5363</a> | <em>Blocker</em> | <strong>Spark 1.2 freeze without error notification</strong></li>
</ul>
<p>After a number of calls to a map().collect() statement Spark freezes without reporting any error. Within the map a large broadcast variable is used.</p>
<p>The freezing can be avoided by setting 'spark.python.worker.reuse = false' (Spark 1.2) or using an earlier version, however, at the prize of low speed.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5361">SPARK-5361</a> | <em>Major</em> | <strong>Multiple Java RDD &lt;-&gt; Python RDD conversions not working correctly</strong></li>
</ul>
<p>This is found through reading RDD from <code>sc.newAPIHadoopRDD</code> and writing it back using <code>rdd.saveAsNewAPIHadoopFile</code> in pyspark.</p>
<p>It turns out that whenever there are multiple RDD conversions from JavaRDD to PythonRDD then back to JavaRDD, the exception below happens:</p>
<p>{noformat} 15/01/16 10:28:31 ERROR Executor: Exception in task 0.0 in stage 3.0 (TID 7) java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to java.util.ArrayList at org.apache.spark.api.python.SerDeUtil$$anonfun$pythonToJava$1$$anonfun$apply$1.apply(SerDeUtil.scala:157) at org.apache.spark.api.python.SerDeUtil$$anonfun$pythonToJava$1$$anonfun$apply$1.apply(SerDeUtil.scala:153) at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371) at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308) {noformat}</p>
<p>The test case code below reproduces it:</p>
<p>{noformat} from pyspark.rdd import RDD</p>
<p>dl = [ (u'2', {u'director': u'David Lean'}), (u'7', {u'director': u'Andrew Dominik'}) ]</p>
<p>dl_rdd = sc.parallelize(dl) tmp = dl_rdd._to_java_object_rdd() tmp2 = sc._jvm.SerDe.javaToPython(tmp) t = RDD(tmp2, sc) t.count()</p>
<p>tmp = t._to_java_object_rdd() tmp2 = sc._jvm.SerDe.javaToPython(tmp) t = RDD(tmp2, sc) t.count() # it blows up here during the 2nd time of conversion {noformat}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5335">SPARK-5335</a> | <em>Major</em> | <strong>Destroying cluster in VPC with &quot;--delete-groups&quot; fails to remove security groups</strong></li>
</ul>
<p>When I try to remove security groups using option of the script, it fails because in VPC one should remove security groups by id, not name as it is now.</p>
<p>{code} $ ./spark-ec2 -k key20141114 -i ~/key.pem --region=eu-west-1 --delete-groups destroy SparkByScript Are you sure you want to destroy the cluster SparkByScript? The following instances will be terminated: Searching for existing cluster SparkByScript... ALL DATA ON ALL NODES WILL BE LOST!! Destroy cluster SparkByScript (y/N): y Terminating master... Terminating slaves... Deleting security groups (this will take some time)... Waiting for cluster to enter 'terminated' state. Cluster is now in 'terminated' state. Waited 0 seconds. Attempt 1 Deleting rules in security group SparkByScript-slaves Deleting rules in security group SparkByScript-master ERROR:boto:400 Bad Request ERROR:boto:&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt; &lt;Response&gt;&lt;Errors&gt;&lt;Error&gt;&lt;Code&gt;InvalidParameterValue&lt;/Code&gt;&lt;Message&gt;Invalid value 'SparkByScript-slaves' for groupName. You may not reference Amazon VPC security groups by name. Please use the corresponding id for this operation.&lt;/Message&gt;&lt;/Error&gt;&lt;/Errors&gt;&lt;RequestID&gt;60313fac-5d47-48dd-a8bf-e9832948c0a6&lt;/RequestID&gt;&lt;/Response&gt; Failed to delete security group SparkByScript-slaves ERROR:boto:400 Bad Request ERROR:boto:&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt; &lt;Response&gt;&lt;Errors&gt;&lt;Error&gt;&lt;Code&gt;InvalidParameterValue&lt;/Code&gt;&lt;Message&gt;Invalid value 'SparkByScript-master' for groupName. You may not reference Amazon VPC security groups by name. Please use the corresponding id for this operation.&lt;/Message&gt;&lt;/Error&gt;&lt;/Errors&gt;&lt;RequestID&gt;74ff8431-c0c1-4052-9ecb-c0adfa7eeeac&lt;/RequestID&gt;&lt;/Response&gt; Failed to delete security group SparkByScript-master Attempt 2 .... {code}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5227">SPARK-5227</a> | <em>Blocker</em> | <strong>InputOutputMetricsSuite &quot;input metrics when reading text file with multiple splits&quot; test fails in branch-1.2 SBT Jenkins build w/hadoop1.0 and hadoop2.0 profiles</strong></li>
</ul>
<p>The InputOutputMetricsSuite &quot; input metrics when reading text file with multiple splits&quot; test has been failing consistently in our new {{branch-1.2}} Jenkins SBT build: https://amplab.cs.berkeley.edu/jenkins/job/Spark-1.2-SBT/14/AMPLAB_JENKINS_BUILD_PROFILE=hadoop2.0,label=centos/testReport/junit/org.apache.spark.metrics/InputOutputMetricsSuite/input_metrics_when_reading_text_file_with_multiple_splits/</p>
<p>Here's the error message</p>
<p>{code} ArrayBuffer(32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 16) had length 3438 instead of expected length 2 {code}</p>
<p>I can't reproduce this issue by running the test in isolation and it also seems to be passing in the pull request builder. I _was_ able to reproduce the error by modifying that test to add a call to</p>
<p>{code} sc.hadoopConfiguration.setLong(&quot;fs.local.block.size&quot;, 32) {code}</p>
<p>It turns out that there's a call to this in WholeTextFileRecordReaderSuite and the execution of that suite happens before the failing InputOutputMetricsSuite test. I've looked through the code and it doesn't look like we have any shared state between those test suites, so I suspect that there could be some Hadoop bug in older versions that's impacting us here (such as global shared state in a Hadoop class that's configured from the first test run and not cleared for the second test).</p>
<p>I don't have the cycles to fix this right now, but it would be great if a Hadoop expert could take a look and see if they can come up with a workaround (or spot a bug in our code).</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5186">SPARK-5186</a> | <em>Major</em> | <strong>Vector.equals and Vector.hashCode are very inefficient and fail on SparseVectors with large size</strong></li>
</ul>
<p>The implementation of Vector.equals and Vector.hashCode are correct but slow for SparseVectors that are truly sparse.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-5153">SPARK-5153</a> | <em>Critical</em> | <strong>Flaky test: o.a.s.streaming.kafka.ReliableKafkaStreamSuite</strong></li>
</ul>
<p>I have seen several irrelevant PR failed on this test</p>
<p>https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/25254/consoleFull</p>
<p>https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/25248/</p>
<p>https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/25251/console</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-4986">SPARK-4986</a> | <em>Blocker</em> | <strong>Graceful shutdown for Spark Streaming does not work in Standalone cluster mode</strong></li>
</ul>
<p>When using the graceful stop API of Spark Streaming in Spark Standalone cluster the stop signal never reaches the receivers. I have tested this with Spark 1.2 and Kafka receivers.</p>
<p>ReceiverTracker will send StopReceiver message to ReceiverSupervisorImpl. In local mode ReceiverSupervisorImpl receives this message but in Standalone cluster mode the message seems to be lost.</p>
<p>(I have modified the code to send my own string message as a stop signal from ReceiverTracker to ReceiverSupervisorImpl and it works as a workaround.)</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-4983">SPARK-4983</a> | <em>Minor</em> | <strong>Add sleep() before tagging EC2 instances to allow instance metadata to propagate</strong></li>
</ul>
<p>We launch EC2 instances in {{spark-ec2}} and then immediately tag them in a separate boto call. Sometimes, EC2 doesn't get enough time to propagate information about the just-launched instances, so when we go to tag them we get a server that doesn't know about them yet.</p>
<p>This yields the following type of error:</p>
<p>{code} Launching instances... Launched 1 slaves in us-east-1b, regid = r-cf780321 Launched master in us-east-1b, regid = r-da7e0534 Traceback (most recent call last): File &quot;./ec2/spark_ec2.py&quot;, line 1284, in &lt;module&gt; main() File &quot;./ec2/spark_ec2.py&quot;, line 1276, in main real_main() File &quot;./ec2/spark_ec2.py&quot;, line 1122, in real_main (master_nodes, slave_nodes) = launch_cluster(conn, opts, cluster_name) File &quot;./ec2/spark_ec2.py&quot;, line 646, in launch_cluster value='{cn}-master-{iid}'.format(cn=cluster_name, iid=master.id)) File &quot;.../spark/ec2/lib/boto-2.34.0/boto/ec2/ec2object.py&quot;, line 80, in add_tag self.add_tags({key: value}, dry_run) File &quot;.../spark/ec2/lib/boto-2.34.0/boto/ec2/ec2object.py&quot;, line 97, in add_tags dry_run=dry_run File &quot;.../spark/ec2/lib/boto-2.34.0/boto/ec2/connection.py&quot;, line 4202, in create_tags return self.get_status('CreateTags', params, verb='POST') File &quot;.../spark/ec2/lib/boto-2.34.0/boto/connection.py&quot;, line 1223, in get_status raise self.ResponseError(response.status, response.reason, body) boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt; &lt;Response&gt;&lt;Errors&gt;&lt;Error&gt;&lt;Code&gt;InvalidInstanceID.NotFound&lt;/Code&gt;&lt;Message&gt;The instance ID 'i-585219a6' does not exist&lt;/Message&gt;&lt;/Error&gt;&lt;/Errors&gt;&lt;RequestID&gt;b9f1ad6e-59b9-47fd-a693-527be1f779eb&lt;/RequestID&gt;&lt;/Response&gt; {code}</p>
<p>The solution is to tag the instances in the same call that launches them, or less desirably, tag the instances after some short wait.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-4905">SPARK-4905</a> | <em>Critical</em> | <strong>Flaky test: o.a.s.streaming.flume.FlumeStreamSuite.flume input stream</strong></li>
</ul>
<p>It looks like the &quot;org.apache.spark.streaming.flume.FlumeStreamSuite.flume input stream&quot; test might be flaky ([link|https://amplab.cs.berkeley.edu/jenkins//job/SparkPullRequestBuilder/24647/testReport/junit/org.apache.spark.streaming.flume/FlumeStreamSuite/flume_input_stream/]):</p>
<p>{code} Error Message</p>
<p>The code passed to eventually never returned normally. Attempted 106 times over 10.045097243 seconds. Last failure message: ArrayBuffer(&quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;) was not equal to Vector(&quot;1&quot;, &quot;2&quot;, &quot;3&quot;, &quot;4&quot;, &quot;5&quot;, &quot;6&quot;, &quot;7&quot;, &quot;8&quot;, &quot;9&quot;, &quot;10&quot;, &quot;11&quot;, &quot;12&quot;, &quot;13&quot;, &quot;14&quot;, &quot;15&quot;, &quot;16&quot;, &quot;17&quot;, &quot;18&quot;, &quot;19&quot;, &quot;20&quot;, &quot;21&quot;, &quot;22&quot;, &quot;23&quot;, &quot;24&quot;, &quot;25&quot;, &quot;26&quot;, &quot;27&quot;, &quot;28&quot;, &quot;29&quot;, &quot;30&quot;, &quot;31&quot;, &quot;32&quot;, &quot;33&quot;, &quot;34&quot;, &quot;35&quot;, &quot;36&quot;, &quot;37&quot;, &quot;38&quot;, &quot;39&quot;, &quot;40&quot;, &quot;41&quot;, &quot;42&quot;, &quot;43&quot;, &quot;44&quot;, &quot;45&quot;, &quot;46&quot;, &quot;47&quot;, &quot;48&quot;, &quot;49&quot;, &quot;50&quot;, &quot;51&quot;, &quot;52&quot;, &quot;53&quot;, &quot;54&quot;, &quot;55&quot;, &quot;56&quot;, &quot;57&quot;, &quot;58&quot;, &quot;59&quot;, &quot;60&quot;, &quot;61&quot;, &quot;62&quot;, &quot;63&quot;, &quot;64&quot;, &quot;65&quot;, &quot;66&quot;, &quot;67&quot;, &quot;68&quot;, &quot;69&quot;, &quot;70&quot;, &quot;71&quot;, &quot;72&quot;, &quot;73&quot;, &quot;74&quot;, &quot;75&quot;, &quot;76&quot;, &quot;77&quot;, &quot;78&quot;, &quot;79&quot;, &quot;80&quot;, &quot;81&quot;, &quot;82&quot;, &quot;83&quot;, &quot;84&quot;, &quot;85&quot;, &quot;86&quot;, &quot;87&quot;, &quot;88&quot;, &quot;89&quot;, &quot;90&quot;, &quot;91&quot;, &quot;92&quot;, &quot;93&quot;, &quot;94&quot;, &quot;95&quot;, &quot;96&quot;, &quot;97&quot;, &quot;98&quot;, &quot;99&quot;, &quot;100&quot;). Stacktrace</p>
<p>sbt.ForkMain$ForkError: The code passed to eventually never returned normally. Attempted 106 times over 10.045097243 seconds. Last failure message: ArrayBuffer(&quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;) was not equal to Vector(&quot;1&quot;, &quot;2&quot;, &quot;3&quot;, &quot;4&quot;, &quot;5&quot;, &quot;6&quot;, &quot;7&quot;, &quot;8&quot;, &quot;9&quot;, &quot;10&quot;, &quot;11&quot;, &quot;12&quot;, &quot;13&quot;, &quot;14&quot;, &quot;15&quot;, &quot;16&quot;, &quot;17&quot;, &quot;18&quot;, &quot;19&quot;, &quot;20&quot;, &quot;21&quot;, &quot;22&quot;, &quot;23&quot;, &quot;24&quot;, &quot;25&quot;, &quot;26&quot;, &quot;27&quot;, &quot;28&quot;, &quot;29&quot;, &quot;30&quot;, &quot;31&quot;, &quot;32&quot;, &quot;33&quot;, &quot;34&quot;, &quot;35&quot;, &quot;36&quot;, &quot;37&quot;, &quot;38&quot;, &quot;39&quot;, &quot;40&quot;, &quot;41&quot;, &quot;42&quot;, &quot;43&quot;, &quot;44&quot;, &quot;45&quot;, &quot;46&quot;, &quot;47&quot;, &quot;48&quot;, &quot;49&quot;, &quot;50&quot;, &quot;51&quot;, &quot;52&quot;, &quot;53&quot;, &quot;54&quot;, &quot;55&quot;, &quot;56&quot;, &quot;57&quot;, &quot;58&quot;, &quot;59&quot;, &quot;60&quot;, &quot;61&quot;, &quot;62&quot;, &quot;63&quot;, &quot;64&quot;, &quot;65&quot;, &quot;66&quot;, &quot;67&quot;, &quot;68&quot;, &quot;69&quot;, &quot;70&quot;, &quot;71&quot;, &quot;72&quot;, &quot;73&quot;, &quot;74&quot;, &quot;75&quot;, &quot;76&quot;, &quot;77&quot;, &quot;78&quot;, &quot;79&quot;, &quot;80&quot;, &quot;81&quot;, &quot;82&quot;, &quot;83&quot;, &quot;84&quot;, &quot;85&quot;, &quot;86&quot;, &quot;87&quot;, &quot;88&quot;, &quot;89&quot;, &quot;90&quot;, &quot;91&quot;, &quot;92&quot;, &quot;93&quot;, &quot;94&quot;, &quot;95&quot;, &quot;96&quot;, &quot;97&quot;, &quot;98&quot;, &quot;99&quot;, &quot;100&quot;). at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:420) at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:438) at org.scalatest.concurrent.Eventually$.eventually(Eventually.scala:478) at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:307) at org.scalatest.concurrent.Eventually$.eventually(Eventually.scala:478) at org.apache.spark.streaming.flume.FlumeStreamSuite.writeAndVerify(FlumeStreamSuite.scala:142) at org.apache.spark.streaming.flume.FlumeStreamSuite.org$apache$spark$streaming$flume$FlumeStreamSuite$$testFlumeStream(FlumeStreamSuite.scala:74) at org.apache.spark.streaming.flume.FlumeStreamSuite$$anonfun$2.apply$mcV$sp(FlumeStreamSuite.scala:62) at org.apache.spark.streaming.flume.FlumeStreamSuite$$anonfun$2.apply(FlumeStreamSuite.scala:62) at org.apache.spark.streaming.flume.FlumeStreamSuite$$anonfun$2.apply(FlumeStreamSuite.scala:62) at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22) at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85) at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104) at org.scalatest.Transformer.apply(Transformer.scala:22) at org.scalatest.Transformer.apply(Transformer.scala:20) at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166) at org.scalatest.Suite$class.withFixture(Suite.scala:1122) at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555) at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163) at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175) at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175) at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306) at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175) at org.apache.spark.streaming.flume.FlumeStreamSuite.org$scalatest$BeforeAndAfter$$super$runTest(FlumeStreamSuite.scala:46) at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200) at org.apache.spark.streaming.flume.FlumeStreamSuite.runTest(FlumeStreamSuite.scala:46) at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208) at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208) at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413) at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) at scala.collection.immutable.List.foreach(List.scala:318) at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401) at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396) at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483) at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208) at org.scalatest.FunSuite.runTests(FunSuite.scala:1555) at org.scalatest.Suite$class.run(Suite.scala:1424) at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555) at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212) at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212) at org.scalatest.SuperEngine.runImpl(Engine.scala:545) at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212) at org.apache.spark.streaming.flume.FlumeStreamSuite.org$scalatest$BeforeAndAfter$$super$run(FlumeStreamSuite.scala:46) at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241) at org.apache.spark.streaming.flume.FlumeStreamSuite.run(FlumeStreamSuite.scala:46) at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:462) at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:671) at sbt.ForkMain$Run$2.call(ForkMain.java:294) at sbt.ForkMain$Run$2.call(ForkMain.java:284) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745) Caused by: sbt.ForkMain$ForkError: ArrayBuffer(&quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;) was not equal to Vector(&quot;1&quot;, &quot;2&quot;, &quot;3&quot;, &quot;4&quot;, &quot;5&quot;, &quot;6&quot;, &quot;7&quot;, &quot;8&quot;, &quot;9&quot;, &quot;10&quot;, &quot;11&quot;, &quot;12&quot;, &quot;13&quot;, &quot;14&quot;, &quot;15&quot;, &quot;16&quot;, &quot;17&quot;, &quot;18&quot;, &quot;19&quot;, &quot;20&quot;, &quot;21&quot;, &quot;22&quot;, &quot;23&quot;, &quot;24&quot;, &quot;25&quot;, &quot;26&quot;, &quot;27&quot;, &quot;28&quot;, &quot;29&quot;, &quot;30&quot;, &quot;31&quot;, &quot;32&quot;, &quot;33&quot;, &quot;34&quot;, &quot;35&quot;, &quot;36&quot;, &quot;37&quot;, &quot;38&quot;, &quot;39&quot;, &quot;40&quot;, &quot;41&quot;, &quot;42&quot;, &quot;43&quot;, &quot;44&quot;, &quot;45&quot;, &quot;46&quot;, &quot;47&quot;, &quot;48&quot;, &quot;49&quot;, &quot;50&quot;, &quot;51&quot;, &quot;52&quot;, &quot;53&quot;, &quot;54&quot;, &quot;55&quot;, &quot;56&quot;, &quot;57&quot;, &quot;58&quot;, &quot;59&quot;, &quot;60&quot;, &quot;61&quot;, &quot;62&quot;, &quot;63&quot;, &quot;64&quot;, &quot;65&quot;, &quot;66&quot;, &quot;67&quot;, &quot;68&quot;, &quot;69&quot;, &quot;70&quot;, &quot;71&quot;, &quot;72&quot;, &quot;73&quot;, &quot;74&quot;, &quot;75&quot;, &quot;76&quot;, &quot;77&quot;, &quot;78&quot;, &quot;79&quot;, &quot;80&quot;, &quot;81&quot;, &quot;82&quot;, &quot;83&quot;, &quot;84&quot;, &quot;85&quot;, &quot;86&quot;, &quot;87&quot;, &quot;88&quot;, &quot;89&quot;, &quot;90&quot;, &quot;91&quot;, &quot;92&quot;, &quot;93&quot;, &quot;94&quot;, &quot;95&quot;, &quot;96&quot;, &quot;97&quot;, &quot;98&quot;, &quot;99&quot;, &quot;100&quot;) at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160) at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6231) at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6265) at org.apache.spark.streaming.flume.FlumeStreamSuite$$anonfun$writeAndVerify$2.apply$mcV$sp(FlumeStreamSuite.scala:149) at org.apache.spark.streaming.flume.FlumeStreamSuite$$anonfun$writeAndVerify$2.apply(FlumeStreamSuite.scala:142) at org.apache.spark.streaming.flume.FlumeStreamSuite$$anonfun$writeAndVerify$2.apply(FlumeStreamSuite.scala:142) at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:394) at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:408) ... 52 more {code}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-4832">SPARK-4832</a> | <em>Minor</em> | <strong>some other processes might take the daemon pid</strong></li>
</ul>
<p>Some other processes might use the pid saved in pid file. In that case we should ignore it and launch daemons.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-4814">SPARK-4814</a> | <em>Major</em> | <strong>Enable assertions in SBT, Maven tests / AssertionError from Hive's LazyBinaryInteger</strong></li>
</ul>
<p>Follow up to SPARK-4159, wherein we noticed that Java tests weren't running in Maven, in part because a Java test actually fails with {{AssertionError}}. That code/test was fixed in SPARK-4850.</p>
<p>The reason it wasn't caught by SBT tests was that they don't run with assertions on, and Maven's surefire does.</p>
<p>Turning on assertions in the SBT build is trivial, adding one line:</p>
<p>{code} javaOptions in Test += &quot;-ea&quot;, {code}</p>
<p>This reveals a test failure in Scala test suites though:</p>
<p>{code} [info] - alter_merge_2 *** FAILED *** (1 second, 305 milliseconds) [info] Failed to execute query using catalyst: [info] Error: Job aborted due to stage failure: Task 1 in stage 551.0 failed 1 times, most recent failure: Lost task 1.0 in stage 551.0 (TID 1532, localhost): java.lang.AssertionError [info] at org.apache.hadoop.hive.serde2.lazybinary.LazyBinaryInteger.init(LazyBinaryInteger.java:51) [info] at org.apache.hadoop.hive.serde2.columnar.ColumnarStructBase$FieldInfo.uncheckedGetField(ColumnarStructBase.java:110) [info] at org.apache.hadoop.hive.serde2.columnar.ColumnarStructBase.getField(ColumnarStructBase.java:171) [info] at org.apache.hadoop.hive.serde2.objectinspector.ColumnarStructObjectInspector.getStructFieldData(ColumnarStructObjectInspector.java:166) [info] at org.apache.spark.sql.hive.HadoopTableReader$$anonfun$fillObject$1.apply(TableReader.scala:318) [info] at org.apache.spark.sql.hive.HadoopTableReader$$anonfun$fillObject$1.apply(TableReader.scala:314) [info] at scala.collection.Iterator$$anon$11.next(Iterator.scala:328) [info] at org.apache.spark.sql.execution.Aggregate$$anonfun$execute$1$$anonfun$6.apply(Aggregate.scala:132) [info] at org.apache.spark.sql.execution.Aggregate$$anonfun$execute$1$$anonfun$6.apply(Aggregate.scala:128) [info] at org.apache.spark.rdd.RDD$$anonfun$13.apply(RDD.scala:615) [info] at org.apache.spark.rdd.RDD$$anonfun$13.apply(RDD.scala:615) [info] at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35) [info] at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:264) [info] at org.apache.spark.rdd.RDD.iterator(RDD.scala:231) [info] at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35) [info] at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:264) [info] at org.apache.spark.rdd.RDD.iterator(RDD.scala:231) [info] at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68) [info] at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41) [info] at org.apache.spark.scheduler.Task.run(Task.scala:56) [info] at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:195) [info] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [info] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [info] at java.lang.Thread.run(Thread.java:745) {code}</p>
<p>The items for this JIRA are therefore:</p>
<ul>
<li>Enable assertions in SBT</li>
<li>Fix this failure</li>
<li>Figure out why Maven scalatest didn't trigger it - may need assertions explicitly turned on too.</li>
</ul>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-4704">SPARK-4704</a> | <em>Major</em> | <strong>SparkSubmitDriverBootstrap doesn't flush output</strong></li>
</ul>
<p>When running spark-submit with a job that immediately blows up (say due to init errors in the job code), there is no error output from spark-submit on the console.</p>
<p>When I ran spark-class directly, then I do see the error/stack trace on the console.</p>
<p>I believe the issue is in SparkSubmitDriverBootstrapper (I had spark.driver.memory set in spark-defaults.conf) not waiting for the RedirectThreads to flush/complete before exiting.</p>
<p>E.g. here:</p>
<p>https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/deploy/SparkSubmitDriverBootstrapper.scala#L143</p>
<p>I believe around line 165 or so, stdoutThread.join() and stderrThread.join() calls are necessary to make sure the other threads have had a chance to flush process.getInputStream/getErrorStream to System.out/err before the process exits.</p>
<p>I've been tripped up by this in similar RedirectThread/process code, hence suspecting this is the problem.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-4631">SPARK-4631</a> | <em>Critical</em> | <strong>Add real unit test for MQTT</strong></li>
</ul>
<p>A real unit test that actually transfers data to ensure that the MQTTUtil is functional</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-4579">SPARK-4579</a> | <em>Major</em> | <strong>Scheduling Delay appears negative</strong></li>
</ul>
<p>!https://cloud.githubusercontent.com/assets/455755/5174438/23d08604-73ff-11e4-9a76-97233b610544.png!</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-4300">SPARK-4300</a> | <em>Minor</em> | <strong>Race condition during SparkWorker shutdown</strong></li>
</ul>
<p>When a shark job is done. there are some error message as following show in the log</p>
<p>{code} INFO 22:10:41,635 SparkMaster: akka.tcp://sparkDriver@ip-172-31-11-204.us-west-1.compute.internal:57641 got disassociated, removing it. INFO 22:10:41,640 SparkMaster: Removing app app-20141106221014-0000 INFO 22:10:41,687 SparkMaster: Removing application Shark::ip-172-31-11-204.us-west-1.compute.internal INFO 22:10:41,710 SparkWorker: Asked to kill executor app-20141106221014-0000/0 INFO 22:10:41,712 SparkWorker: Runner thread for executor app-20141106221014-0000/0 interrupted INFO 22:10:41,714 SparkWorker: Killing process! ERROR 22:10:41,738 SparkWorker: Error writing stream to file /var/lib/spark/work/app-20141106221014-0000/0/stdout ERROR 22:10:41,739 SparkWorker: java.io.IOException: Stream closed ERROR 22:10:41,739 SparkWorker: at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162) ERROR 22:10:41,740 SparkWorker: at java.io.BufferedInputStream.read1(BufferedInputStream.java:272) ERROR 22:10:41,740 SparkWorker: at java.io.BufferedInputStream.read(BufferedInputStream.java:334) ERROR 22:10:41,740 SparkWorker: at java.io.FilterInputStream.read(FilterInputStream.java:107) ERROR 22:10:41,741 SparkWorker: at org.apache.spark.util.logging.FileAppender.appendStreamToFile(FileAppender.scala:70) ERROR 22:10:41,741 SparkWorker: at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply$mcV$sp(FileAppender.scala:39) ERROR 22:10:41,741 SparkWorker: at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply(FileAppender.scala:39) ERROR 22:10:41,742 SparkWorker: at org.apache.spark.util.logging.FileAppender$$anon$1$$anonfun$run$1.apply(FileAppender.scala:39) ERROR 22:10:41,742 SparkWorker: at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1311) ERROR 22:10:41,742 SparkWorker: at org.apache.spark.util.logging.FileAppender$$anon$1.run(FileAppender.scala:38) INFO 22:10:41,838 SparkMaster: Connected to Cassandra cluster: 4299 INFO 22:10:41,839 SparkMaster: Adding host 172.31.11.204 (Analytics) INFO 22:10:41,840 SparkMaster: New Cassandra host /172.31.11.204:9042 added INFO 22:10:41,841 SparkMaster: Adding host 172.31.11.204 (Analytics) INFO 22:10:41,842 SparkMaster: Adding host 172.31.11.204 (Analytics) INFO 22:10:41,852 SparkMaster: akka.tcp://sparkDriver@ip-172-31-11-204.us-west-1.compute.internal:57641 got disassociated, removing it. INFO 22:10:41,853 SparkMaster: akka.tcp://sparkDriver@ip-172-31-11-204.us-west-1.compute.internal:57641 got disassociated, removing it. INFO 22:10:41,853 SparkMaster: akka.tcp://sparkDriver@ip-172-31-11-204.us-west-1.compute.internal:57641 got disassociated, removing it. INFO 22:10:41,857 SparkMaster: akka.tcp://sparkDriver@ip-172-31-11-204.us-west-1.compute.internal:57641 got disassociated, removing it. INFO 22:10:41,862 SparkMaster: Adding host 172.31.11.204 (Analytics) WARN 22:10:42,200 SparkMaster: Got status update for unknown executor app-20141106221014-0000/0 INFO 22:10:42,211 SparkWorker: Executor app-20141106221014-0000/0 finished with state KILLED exitStatus 143 {code}</p>
<p>/var/lib/spark/work/app-20141106221014-0000/0/stdout is on the disk. It is trying to write to a close IO stream.</p>
<p>Spark worker shuts down by {code} private def killProcess(message: Option[String]) { var exitCode: Option[Int] = None logInfo(&quot;Killing process!&quot;) process.destroy() process.waitFor() if (stdoutAppender != null) { stdoutAppender.stop() } if (stderrAppender != null) { stderrAppender.stop() } if (process != null) { exitCode = Some(process.waitFor()) } worker ! ExecutorStateChanged(appId, execId, state, message, exitCode)</p>
<p>{code}</p>
<p>But stdoutAppender concurrently writes to output log file, which creates race condition.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-4267">SPARK-4267</a> | <em>Blocker</em> | <strong>Failing to launch jobs on Spark on YARN with Hadoop 2.5.0 or later</strong></li>
</ul>
<p>Currently we're trying Spark on YARN included in Hadoop 2.5.1. Hadoop 2.5 uses protobuf 2.5.0 so I compiled with protobuf 2.5.1 like this:</p>
<p>{code} ./make-distribution.sh --name spark-1.1.1 --tgz -Pyarn -Dhadoop.version=2.5.1 -Dprotobuf.version=2.5.0 {code}</p>
<p>Then Spark on YARN fails to launch jobs with NPE.</p>
<p>{code} $ bin/spark-shell --master yarn-client scala&gt; sc.textFile(&quot;hdfs:///user/ozawa/wordcountInput20G&quot;).flatMap(line =&gt; line.split(&quot; &quot;)).map(word =&gt; (word, 1)).persist().reduceByKey((a, b) =&gt; a + b, 16).saveAsTextFile(&quot;hdfs:///user/ozawa/sparkWordcountOutNew2&quot;); java.lang.NullPointerException<br />
at org.apache.spark.SparkContext.defaultParallelism(SparkContext.scala:1284) at org.apache.spark.SparkContext.defaultMinPartitions(SparkContext.scala:1291)<br />
at org.apache.spark.SparkContext.textFile$default$2(SparkContext.scala:480) at $iwC$$iwC$$iwC$$iwC.&lt;init&gt;(&lt;console&gt;:13)<br />
at $iwC$$iwC$$iwC.&lt;init&gt;(&lt;console&gt;:18) at $iwC$$iwC.&lt;init&gt;(&lt;console&gt;:20)<br />
at $iwC.&lt;init&gt;(&lt;console&gt;:22) at &lt;init&gt;(&lt;console&gt;:24)<br />
at .&lt;init&gt;(&lt;console&gt;:28) at .&lt;clinit&gt;(&lt;console&gt;)<br />
at .&lt;init&gt;(&lt;console&gt;:7) at .&lt;clinit&gt;(&lt;console&gt;)<br />
at $print(&lt;console&gt;) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br />
at java.lang.reflect.Method.invoke(Method.java:606) at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:789)<br />
at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1062) at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:615)<br />
at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:646) at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:610)<br />
at org.apache.spark.repl.SparkILoop.reallyInterpret$1(SparkILoop.scala:823) at org.apache.spark.repl.SparkILoop.interpretStartingWith(SparkILoop.scala:868)<br />
at org.apache.spark.repl.SparkILoop.command(SparkILoop.scala:780) at org.apache.spark.repl.SparkILoop.processLine$1(SparkILoop.scala:625)<br />
at org.apache.spark.repl.SparkILoop.innerLoop$1(SparkILoop.scala:633) at org.apache.spark.repl.SparkILoop.loop(SparkILoop.scala:638)<br />
at org.apache.spark.repl.SparkILoop$$anonfun$process$1.apply$mcZ$sp(SparkILoop.scala:963) at org.apache.spark.repl.SparkILoop$$anonfun$process$1.apply(SparkILoop.scala:911)<br />
at org.apache.spark.repl.SparkILoop$$anonfun$process$1.apply(SparkILoop.scala:911) at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)<br />
at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:911) at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:1006)<br />
at org.apache.spark.repl.Main$.main(Main.scala:31) at org.apache.spark.repl.Main.main(Main.scala)<br />
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br />
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606)<br />
at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:329) at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)<br />
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala) {code}</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-3266">SPARK-3266</a> | <em>Major</em> | <strong>JavaDoubleRDD doesn't contain max()</strong></li>
</ul>
<p>While I can compile my code, I see:</p>
<p>Caused by: java.lang.NoSuchMethodError: org.apache.spark.api.java.JavaDoubleRDD.max(Ljava/util/Comparator;)Ljava/lang/Double;</p>
<p>When I try to execute my Spark code. Stepping into the JavaDoubleRDD class, I don't notice max() although it is clearly listed in the documentation.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-2472">SPARK-2472</a> | <em>Minor</em> | <strong>Spark SQL Thrift server sometimes assigns wrong job group name</strong></li>
</ul>
<p>Sample beeline session used to reproduce this issue:</p>
<p>{code} 0: jdbc:hive2://localhost:10000&gt; drop table test; +---------+ | result | +---------+ +---------+ No rows selected (0.614 seconds) 0: jdbc:hive2://localhost:10000&gt; create table hive_table_copy as select * from hive_table; +------+--------+ | key | value | +------+--------+ +------+--------+ No rows selected (0.493 seconds) 0 {code}</p>
<p>The second statement results in two stages, the first stage is labeled with the first {{drop table}} statement rather than the CTAS statement.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-1955">SPARK-1955</a> | <em>Minor</em> | <strong>VertexRDD can incorrectly assume index sharing</strong></li>
</ul>
<p>Many VertexRDD operations (diff, leftJoin, innerJoin) can use a fast zip join if both operands are VertexRDDs sharing the same index (i.e., one operand is derived from the other). This check is implemented by matching on the operand type and using the fast join strategy if both are VertexRDDs.</p>
<p>This is clearly fine when both do in fact share the same index. It is also fine when the two VertexRDDs have the same partitioner but different indexes, because each VertexPartition will detect the index mismatch and fall back to the slow but correct local join strategy.</p>
<p>However, when they have different numbers of partitions or different partition functions, an exception or even silently incorrect results can occur.</p>
<p>For example:</p>
<p>{code} import org.apache.spark._ import org.apache.spark.graphx._</p>
<p>// Construct VertexRDDs with different numbers of partitions val a = VertexRDD(sc.parallelize(List((0L, 1), (1L, 2)), 1)) val b = VertexRDD(sc.parallelize(List((0L, 5)), 8)) // Try to join them. Appears to work... val c = a.innerJoin(b) { (vid, x, y) =&gt; x + y } // ... but then fails with java.lang.IllegalArgumentException: Can't zip RDDs with unequal numbers of partitions c.collect</p>
<p>// Construct VertexRDDs with different partition functions val a = VertexRDD(sc.parallelize(List((0L, 1), (1L, 2))).partitionBy(new HashPartitioner(2))) val bVerts = sc.parallelize(List((1L, 5))) val b = VertexRDD(bVerts.partitionBy(new RangePartitioner(2, bVerts))) // Try to join them. We expect (1L, 7). val c = a.innerJoin(b) { (vid, x, y) =&gt; x + y } // Silent failure: we get an empty set! c.collect {code}</p>
<p>VertexRDD should check equality of partitioners before using the fast zip join. If the partitioners are different, the two datasets should be automatically co-partitioned.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-1911">SPARK-1911</a> | <em>Major</em> | <strong>Warn users if their assembly jars are not built with Java 6</strong></li>
</ul>
<p>The root cause of the problem is detailed in: https://issues.apache.org/jira/browse/SPARK-1520.</p>
<p>In short, an assembly jar built with Java 7+ is not always accessible by Python or other versions of Java (especially Java 6). If the assembly jar is not built on the cluster itself, this problem may manifest itself in strange exceptions that are not trivial to debug. This is an issue especially for PySpark on YARN, which relies on the python files included within the assembly jar.</p>
<p>Currently we warn users only in make-distribution.sh, but most users build the jars directly. At the very least we need to emphasize this in the docs (currently missing entirely). The next step is to add a warning prompt in the mvn scripts whenever Java 7+ is detected.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-1600">SPARK-1600</a> | <em>Major</em> | <strong>flaky &quot;recovery with file input stream&quot; test in streaming.CheckpointSuite</strong></li>
</ul>
<p>the case &quot;recovery with file input stream.recovery with file input stream &quot; sometimes fails when the Jenkins is very busy with an unrelated change</p>
<p>I have met it for 3 times, I also saw it in other places,</p>
<p>the latest example is in</p>
<p>https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/14397/</p>
<p>where the modification is just in YARN related files....</p>
<p>I once reported in dev mail list: http://apache-spark-developers-list.1001551.n3.nabble.com/a-weird-test-case-in-Streaming-td6116.html</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-794">SPARK-794</a> | <em>Major</em> | <strong>Remove sleep() in ClusterScheduler.stop</strong></li>
</ul>
<p>This temporary change made a while back slows down the unit tests quite a bit.</p>
<hr />
<ul>
<li><a href="https://issues.apache.org/jira/browse/SPARK-677">SPARK-677</a> | <em>Major</em> | <strong>PySpark should not collect results through local filesystem</strong></li>
</ul>
<p>Py4J is slow when transferring large arrays, so PySpark currently dumps data to the disk and reads it back in order to collect() RDDs. On large enough datasets, this data will spill from the buffer cache and write to the physical disk, resulting in terrible performance.</p>
<p>Instead, we should stream the data from Java to Python over a local socket or a FIFO.</p>
